export * from './components/index.js'
export { compile, CompileError, type CompileIssue } from './compile.js'
export { render, toTemplate, type RenderOptions, type RenderResult } from './render.js'
export { parseClasses, themeFromConfig, type TailwindConfig, type ParsedClasses } from './tailwind/tailwind.js'
export { buildDocumentV2, registerFonts, AGT_QR } from './core/render.js'
export { ensureFiscalBlocks, FISCAL_BLOCKS } from './core/fiscal.js'
export { contrast, legible, MIN_FISCAL_CONTRAST } from './core/color.js'
export { sampleDocument } from './core/sample.js'
export type { TemplateV2, Block, Style, StyleRef, DocumentData, DocumentLine, DocumentParty, RenderWarning, FiscalPart } from './core/types.js'
